### ISSUE TITLE
Stuck on loading screen after clicking "Select an APK"

### ISSUE THREAD

**Issue by hidp123** [Simizfo/WSATools#11] opened 2021-12-02 22:41 UTC
Hi, when I run WSATools I get the option to load apk. Once I click on the button the loading screen comes but then no progress.

I'm on Windows 11 stable build, developer mode enabled, on "continuous" setting. I manage to install apks using another tool known as WSAtoolbox. 

See screenshots.

![image](https://user-images.githubusercontent.com/84683703/144514662-f6bf63f8-3b0a-406a-8a44-e442ce40f804.png)

![image](https://user-images.githubusercontent.com/84683703/144514699-fd3622dc-2019-45a4-8b99-2f3ebf41c85d.png)

**Comment by Simizfo** [comment] 2021-12-03 14:48
Hi, thanks for reporting!

This is caused by the bug reported on ticket #2 

I'll be working on a fix to be released on the next version of WSATools 👍

**Comment by Simizfo** [comment] 2021-12-03 14:53
Issue #2 has [a temporary solution to this issue. ](https://github.com/Simizfo/WSATools/issues/2#issuecomment-985582680)

**Comment by CelloRJ** [comment] 2021-12-20 00:37
I just renamed the **adb** folder to **adb1** and it worked!

**Comment by Simizfo** [comment] 2022-01-01 10:56
This should be fixed, will be available when 0.2.0 releases.

Thanks for reporting!

**Closed by Simizfo** 2022-01-01 10:56 UTC
Labels: bug
