### ISSUE TITLE
adb.exe: more than one device/emulator

### ISSUE THREAD

**Issue by Your-Best-Friend86** [Simizfo/WSATools#35] opened 2022-06-13 05:06 UTC
I get this error: `adb.exe: more than one device/emulator` when I'm trying to use WSA Tools, adb is installed by WSA Tools and I have these enable and already done:

- Windows 11

- Windows Subsystem for Android app

- Inside it, enable "Developer Mode" and set the Subsystem Resources to "Continuous"

(I'm just testing this system so I downloaded a random app to try)

![image](https://user-images.githubusercontent.com/80213487/173283666-e76c385d-364f-4e6b-b130-fe4e533ebd30.png)

**Comment by Your-Best-Friend86** [comment] 2022-06-13 05:16
I tried to use `adb devices` first to see what I have then I did `kill-server` and tried the adb devices again and there was 1 result and after running the WSA Tools I got which one I should terminate so I used the commed adb kill-server but this time with the exact name of the unnecessary operation and it was successful but then after doing a Retry in WAS Tools, same thing happend again and the unnecessary operation was running

**Comment by Simizfo** [comment] 2022-06-14 07:25
Duplicate of #34, closing

**Closed by Simizfo** 2022-06-14 07:25 UTC
