### ISSUE TITLE
Create/Restore from backup error

### ISSUE THREAD

**Issue by shumashv1** [Simizfo/WSATools#66] opened 2023-10-31 18:23 UTC
Error attempting to restore a backup reads as follows

Something unexpected happened.  Please report this to the developer, thank you!  Here are more details. The system cannot find the file specified. (0x80070002)

**Comment by Simizfo** [comment] 2024-01-13 17:02
Duplicate of #59

**Closed as completed by Simizfo** 2024-01-13 17:02 UTC
Labels: bug
