### ISSUE TITLE
Backup can't be restored, see attached screenshot

### ISSUE THREAD

**Issue by wonkxin** [Simizfo/WSATools#70] opened 2023-11-14 23:57 UTC
![WSAtools_BackupRestore_Error](https://github.com/Simizfo/WSATools/assets/49319011/c4302a28-2251-45dd-a798-067f5fa528ed)

@https://github.com/Simizfo/WSATools/issues/59
After renaming userdata.2.vhdx to userdata.vhdx for the restore process, the backup could be restored, but after that, the apps didn't appear in WSA/Apps

**Comment by binaryn3xus** [comment] 2024-01-10 02:28
I get this similar error trying to do a backup

**Comment by Simizfo** [comment] 2024-01-13 16:58
Hi there. Backups aren't working anymore due to a change that Microsoft made to WSA.

I still haven't had time in these last months to make a fix. Sorry about that.

**Comment by Simizfo** [comment] 2024-01-13 17:02
Closing, this is a duplicate of #59, check that issue for updates.

**Closed as completed by Simizfo** 2024-01-13 17:02 UTC
Labels: bug
